version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_ecommerce_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "start"]
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8008:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - web

networks:
  web:
    driver: bridge
